services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 0.5s
      retries: 100
      start_period: 0.5s
      timeout: 10s

  init:
    build: .
    command: python init_db.py
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TASKS=30
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=test
      - MYSQL_PORT=3306

  worker:
    build: .
    command: python worker.py
    deploy:
      replicas: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=test
      - MYSQL_PORT=3306
